module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'type-case': [2, 'always', 'lower-case'],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'docs',
        'test',
        'chore',
        'build',
        'ci',
        'style',
        'revert',
        'release',
      ],
    ],
    'scope-case': [2, 'always', 'kebab-case'],
    'scope-empty': [2, 'never'],
    'scope-enum': [
      2,
      'always',
      [
        'startup',
        'splash',
        'core',
        'electron',
        'node',
        'browser',
        'common',
        'problem-ui',
        'problem-list',
        'problem-meta',
        'compile-run',
        'sample-test',
        'clangd',
        'competitive-companion',
        'judge',
        'storage',
        'workspace',
        'theme',
        'ui',
        'extensions',
        'build',
        'tooling',
        'deps',
        'release',
        'ci',
        'docs',
      ],
    ],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'body-leading-blank': [1, 'always'],
    'body-max-line-length': [2, 'always', 120],
    'footer-leading-blank': [1, 'always'],
    'footer-max-line-length': [2, 'always', 120],
  },
};
